version: '3'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    tty: true
    restart: always
    #    volumes:
    # - pg_data:/var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-api
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    environment:
      - "DATABASE_HOST=db"
      - "DATABASE_PORT=5432"
      - "DATABASE_USER=postgres"
      - "DATABASE_PASSWORD=password"
    depends_on:
      - db
volumes:
  pg_data:
    driver: local
